### ISSUE TITLE
First stable version 

### ISSUE THREAD

**Issue by abearab** [abearab/ScreenPro2#7]
## Aims
- Improve statistical methods to measure phenotype scores 
- Python 3 stable version and make it easier for users to run the pipeline
## To-do list
- [X] Documentation: <https://screenpro2.readthedocs.io>.
- [ ] `pip` installation
- [ ] FDR calculation
    - https://stackoverflow.com/questions/25185205/calculating-adjusted-p-values-in-python
- [ ] How to set up _Experiment config file_ to measure phenotype scores OR come up with an alternative way to use the pipeline 
- [ ] Include all V2 and V3 library references
- [ ] Provide demo dataset for V2 and V3 library
- [X] Score normalization – __INC__ module, Including Negative Controls
