### ISSUE TITLE
Improve data analysis experience

### ISSUE THREAD

**Issue by abearab** [abearab/ScreenPro2#8]
## To-do list 
- [ ] `conda` installation
- [ ] Build python [dash app](https://plotly.com/dash/) from datasets of screens
- [ ] Exploratory Data Analysis (EDA) in Jupyter notebook
  - [ ] Design python class for results
  - [ ] Load data and make custom graphs – python
  - [ ] Compatibility with [CanDI](https://candi.readthedocs.io/)
